CREATE TABLE IF NOT EXISTS `processed_events` (
    `event_id` VARCHAR(255) PRIMARY KEY,
    `processed_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
