-- Keep test schema compatible with JPA IDENTITY mappings used by auth tests.
SET FOREIGN_KEY_CHECKS = 0;
ALTER TABLE roles MODIFY COLUMN role_id BIGINT NOT NULL AUTO_INCREMENT;
ALTER TABLE users MODIFY COLUMN user_id BIGINT NOT NULL AUTO_INCREMENT;
SET FOREIGN_KEY_CHECKS = 1;
