-- V2__backfill_read_models.sql
-- Direct SQL backfilling has been migrated to a programmatic startup runner (AdminReportingBackfillRunner)
-- to allow the service to be deployed in isolated database-per-service environments (without cross-schema access).
